import Header from '@/components/Header/Header';
import './globals.css';
import { Aclonica } from 'next/font/google';

export const metadata = {
	title: 'Greek Bite',
	description: 'Generated by create next app',
};

const aclonica = Aclonica({
	variable: '--aclonica-font',
	subsets: ['latin'],
	weight: '400',
	display: 'swap',
});

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={`${aclonica.variable}`}>
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
